# Generated by Django 5.0.6 on 2024-08-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Админы')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/foods/', verbose_name='Фото')),
                ('weight', models.IntegerField(blank=True, verbose_name='Масса еды')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Имя')),
                ('status', models.CharField(choices=[('EX', 'Exists'), ('EM', 'Empty')], default='EX', max_length=250, verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена в руб за час')),
            ],
            options={
                'verbose_name': 'Еда/Закуска',
                'verbose_name_plural': 'Еды/Закуски',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/halls/', verbose_name='Аватарка пользователя')),
                ('max_people', models.IntegerField(blank=True, verbose_name='Макс. человек')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Имя зала')),
                ('status', models.CharField(choices=[('FR', 'Free'), ('BS', 'Busy')], default='FR', max_length=250, verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена в руб за час')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('photo', models.ImageField(null=True, upload_to='static/media/users/', verbose_name='Аватарка пользователя')),
                ('tg_username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('user_theme', models.CharField(choices=[('DK', 'Dark'), ('LI', 'Light')], default='LI', max_length=250, verbose_name='Цвет приложения')),
                ('phone_number', models.CharField(max_length=200, null=True, verbose_name='Номер телефона')),
                ('reg_date', models.DateField(auto_now=True, verbose_name='Время регистрации')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.DateTimeField(verbose_name='Время бронирования')),
                ('booking_time', models.IntegerField(verbose_name='Количество забронированных часов')),
                ('foods', models.ManyToManyField(blank=True, related_name='bookings', to='api.foods')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.halls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'Забронировано',
                'verbose_name_plural': 'Забронированы',
            },
        ),
    ]
