# Generated by Django 5.0.6 on 2024-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время создания брони'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
    ]
