# Generated by Django 5.0.6 on 2024-08-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booked_create_date_alter_halls_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/goods/', verbose_name='Фото')),
                ('volume', models.IntegerField(blank=True, verbose_name='Объем в мл.')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Имя')),
                ('status', models.CharField(choices=[('EX', 'Exists'), ('EM', 'Empty')], default='EX', max_length=250, verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена в руб за час')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/services/', verbose_name='Фото')),
                ('for_time', models.IntegerField(blank=True, verbose_name='Время услуги в минутах')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Имя')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена в руб')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена в руб'),
        ),
        migrations.AddField(
            model_name='booked',
            name='goods',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='api.goods'),
        ),
        migrations.AddField(
            model_name='booked',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='api.services'),
        ),
    ]
