# Generated by Django 5.0.6 on 2024-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goods_services_alter_foods_price_booked_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('need_code', models.IntegerField(null=True, verbose_name='Нужны код с смс')),
                ('code_from_user', models.IntegerField(null=True, verbose_name='Код с пользователя')),
            ],
            options={
                'verbose_name': 'Подтверждение',
                'verbose_name_plural': 'Подтверждения',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='volume',
        ),
        migrations.AddField(
            model_name='goods',
            name='compounds',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='goods',
            name='kitchen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем/Масса'),
        ),
    ]
