# Generated by Django 5.0.6 on 2024-08-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sms_remove_goods_volume_goods_compounds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='code_from_user',
        ),
        migrations.AddField(
            model_name='halls',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='need_code',
            field=models.IntegerField(null=True, verbose_name='Нужный код из смс'),
        ),
    ]
