# Generated by Django 5.0.6 on 2024-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_cartfood_cart_foods_cartgoods_cart_goods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='compounds',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='kitchen',
        ),
        migrations.AddField(
            model_name='foods',
            name='compounds',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='foods',
            name='kitchen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена в руб'),
        ),
    ]
