# Generated by Django 5.0.6 on 2024-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_goods_compounds_remove_goods_kitchen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=250, verbose_name='Telegram ID')),
                ('msg', models.TextField(null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Подтверждение',
                'verbose_name_plural': 'Подтверждения',
            },
        ),
        migrations.AddField(
            model_name='booked',
            name='reminder_sent_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booked',
            name='reminder_sent_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booked',
            name='reminder_sent_week',
            field=models.BooleanField(default=False),
        ),
    ]
