# Generated by Django 5.0.6 on 2024-08-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notify_booked_reminder_sent_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
        migrations.RemoveField(
            model_name='booked',
            name='user',
        ),
        migrations.AlterField(
            model_name='foods',
            name='status',
            field=models.CharField(choices=[('EX', 'Exists'), ('EM', 'Empty'), ('PR', 'Present')], default='EX', max_length=250, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Объем/Масса'),
        ),
        migrations.CreateModel(
            name='Presents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
            },
        ),
    ]
