# Generated by Django 5.0.6 on 2024-09-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchentypes', models.CharField(max_length=300, verbose_name='Типы кухни')),
            ],
            options={
                'verbose_name': 'Данные фильтров',
                'verbose_name_plural': 'Данные фильтров',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=300, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Номер техподдержки',
                'verbose_name_plural': 'Номер техподдержки',
            },
        ),
        migrations.RemoveField(
            model_name='cartfood',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartgoods',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cartgoods',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booked',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='booked',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='booked',
            name='services',
        ),
        migrations.AddField(
            model_name='booked',
            name='order_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='book_time',
            field=models.DateTimeField(null=True, verbose_name='Время бронирования'),
        ),
        migrations.AddField(
            model_name='user',
            name='booking_time',
            field=models.IntegerField(null=True, verbose_name='Количество забронированных часов'),
        ),
        migrations.AddField(
            model_name='user',
            name='foods',
            field=models.JSONField(null=True, verbose_name='Еда'),
        ),
        migrations.AddField(
            model_name='user',
            name='goods',
            field=models.JSONField(null=True, verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='user',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.halls'),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.JSONField(null=True, verbose_name='Услуги'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartFood',
        ),
        migrations.DeleteModel(
            name='CartGoods',
        ),
        migrations.DeleteModel(
            name='CartService',
        ),
    ]
