# Generated by Django 5.0.6 on 2024-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_booked_order_data_alter_halls_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_theme',
            field=models.CharField(choices=[('DK', 'Dark'), ('LI', 'Light')], max_length=250, null=True, verbose_name='Цвет приложения'),
        ),
    ]
